### ISSUE TITLE
Feature request: xiaomi_lywsd03mmc sensor support

### ISSUE THREAD

**Issue by vzoltan** [ESPresense/ESPresense.github.io#27]
Hi, could you please add xiaomi_lywsd03mmc temperature/humidity sensor too ?

it works with esp32 if that helps, and also integrated with esphome to home assistant

this is its config in ESPHome in Hme assistant

```
substitutions:
  esphome_name: esp32tempserver

esphome:
  name: ${esphome_name}
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 192.168.2.207
    gateway: 192.168.2.1
    subnet: 255.255.255.0

logger:

api:
  reboot_timeout: 60min
  password: Password

ota:
  password: Password

time:
  - platform: homeassistant
  
esp32_ble_tracker:

sensor:

  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:F1:8E:0D
    id: xiaomisensor_livingroom
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Living room Temperature"
    humidity:
      name: "Living room Humidity"
    battery_level:
      name: "Living room Battery Level"
      
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:71:06:2F
    id: xiaomisensor_bedroom
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    battery_level:
      name: "Bedroom Battery Level"
      
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:B6:A1:6D
    id: xiaomisensor_bathroom
    bindkey: "05e04076be48f427f3d90e166d0fbd5e"
    temperature:
      name: "Bathroom Temperature"
    humidity:
      name: "Bathroom Humidity"
    battery_level:
      name: "Bathroom Battery Level"
```
